  version: '3.3'
  networks:
    forum-network:
      driver: bridge
  services:
    redis:
          image: redis
          container_name: redis
          networks:
            - forum-network
    springBootAdmin:
          image: banditnunes/spring-boot-admin:0.0.1-SNAPSHOT
          container_name: spring_boot_admin
          networks:
            - forum-network
          ports:
             - "8083:8083"
          depends_on:
              - redis
              - springBootForum
    springBootForum:
          image: banditnunes/forum:0.0.1-SNAPSHOT
          container_name: spring_boot_forums
          networks:
            - forum-network
          ports:
            - "8082:8082"
          depends_on:
          - redis


